@startuml

actor 管理员
actor 用户
actor 老师
actor 学生

用户 <|-- 学生
用户 <|-- 老师
用户 <|-- 管理员
学生 <|-- 老师

package   用户用例集 {
    用户 -up-> (登录)
    用户 -up-> (登出)
    用户 -up-> (查看个人资料)
    用户 -up-> (修改个人资料)
    用户 -up-> (修改登录密码)
}
package   业务用例集 {

    学生 --> (选择课程)
    学生 --> (查看成绩)
    学生 --> (学生列表)
    学生 --> (查看已选课程)
    学生 --> (退选已选课程)

    老师 --> (评定成绩)
    老师 --> (查询实验)
    老师 --> (增加实验)
    老师 --> (删除实验)
    老师 --> (编辑实验信息)
}

package   管理员用例集 {
    管理员 --> (查询用户)
    管理员 --> (增加老师用户)
    管理员 --> (增加学生用户)
    管理员 --> (冻结用户)

    管理员 --> (查询课程)
    管理员 --> (增加课程)
    管理员 --> (删除课程)
}

@enduml